import assert from "node:assert/strict";import{test}from"node:test";import{buildSecurityHeaders,createCsrfToken,verifyCsrfToken,encryptAes256Gcm,decryptAes256Gcm,hashPassword,verifyPassword,SlidingWindowLimiter,maskEmail,redactObject,assertSafeOutboundUrl}from"./src/index.js";
test("security headers",()=>{const h=buildSecurityHeaders({nonce:"fixed",production:true});assert.match(h["Content-Security-Policy"],/nonce-fixed/);assert.equal(h["X-Frame-Options"],"DENY");assert.ok(h["Strict-Transport-Security"]);});
test("CSRF is session-bound",()=>{const t=createCsrfToken("a","s");assert.equal(verifyCsrfToken("a",t,"s"),true);assert.equal(verifyCsrfToken("b",t,"s"),false);});
test("AES-GCM detects tampering",()=>{const k=Buffer.alloc(32,7),p=encryptAes256Gcm("secret",k);assert.equal(decryptAes256Gcm(p,k),"secret");const raw=Buffer.from(p,"base64url"); raw[raw.length-1]^=1; assert.throws(()=>decryptAes256Gcm(raw.toString("base64url"),k));});
test("password hashing rejects parameter tampering",()=>{const h=hashPassword("correct horse battery staple"),p=h.split("$");p[1]="262144";assert.equal(verifyPassword("correct horse battery staple",p.join("$")),false);});
test("password hashing and verification",()=>{const h=hashPassword("correct horse battery staple");assert.equal(verifyPassword("correct horse battery staple",h),true);assert.equal(verifyPassword("wrong password",h),false);assert.notEqual(hashPassword("correct horse battery staple"),h);});
test("bounded sliding window",()=>{const l=new SlidingWindowLimiter({limit:2,windowMs:1000,maxKeys:2});assert.equal(l.check("a",1000).allowed,true);assert.equal(l.check("a",1001).allowed,true);assert.equal(l.check("a",1002).allowed,false);l.check("b",2000);l.check("c",2001);assert.ok(l.size()<=2);});
test("PII redaction",()=>{assert.equal(maskEmail("person@example.com"),"p***@example.com");assert.deepEqual(redactObject({password:"x",nested:{token:"y"},ok:"z"}),{password:"[REDACTED]",nested:{token:"[REDACTED]"},ok:"z"});});
test("SSRF blocks loopback and private IPv4/IPv4-mapped IPv6",async()=>{await assert.rejects(()=>assertSafeOutboundUrl("http://127.0.0.1"));await assert.rejects(()=>assertSafeOutboundUrl("http://[::ffff:127.0.0.1]"));await assert.rejects(()=>assertSafeOutboundUrl("http://192.168.1.1"));});
