CREATE TYPE "RecordStatus" AS ENUM ('ACTIVE','INACTIVE');
CREATE TYPE "OrderStatus" AS ENUM ('DRAFT','CONFIRMED','CANCELLED','COMPLETED');
CREATE TYPE "JournalStatus" AS ENUM ('DRAFT','POSTED','VOID');
CREATE TYPE "EmployeeStatus" AS ENUM ('ACTIVE','ON_LEAVE','TERMINATED');
CREATE TYPE "PayrollStatus" AS ENUM ('DRAFT','APPROVED','PAID');
CREATE TYPE "LeadStatus" AS ENUM ('NEW','QUALIFIED','CONVERTED','LOST');
CREATE TYPE "OpportunityStatus" AS ENUM ('OPEN','WON','LOST');
CREATE TYPE "ProjectStatus" AS ENUM ('PLANNING','ACTIVE','ON_HOLD','COMPLETED','CANCELLED');
CREATE TYPE "ManufacturingStatus" AS ENUM ('PLANNED','RELEASED','IN_PROGRESS','COMPLETED','CANCELLED');
CREATE TABLE "Organization" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"name" TEXT NOT NULL,"code" TEXT NOT NULL,"status" "RecordStatus" NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE "BusinessUnit" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"organizationId" UUID NOT NULL REFERENCES "Organization"("id") ON DELETE CASCADE,"name" TEXT NOT NULL,"code" TEXT NOT NULL,"status" "RecordStatus" NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE "Currency" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"decimalPlaces" INTEGER NOT NULL DEFAULT 2,"status" "RecordStatus" NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE "UnitOfMeasure" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"status" "RecordStatus" NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE "ProductCategory" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"name" TEXT NOT NULL,"code" TEXT NOT NULL,"status" "RecordStatus" NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE "Product" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"categoryId" UUID,"uomId" UUID NOT NULL REFERENCES "UnitOfMeasure"("id") ON DELETE RESTRICT,"sku" TEXT NOT NULL,"name" TEXT NOT NULL,"status" "RecordStatus" NOT NULL DEFAULT 'ACTIVE',FOREIGN KEY ("categoryId") REFERENCES "ProductCategory"("id") ON DELETE SET NULL);
CREATE TABLE "Warehouse" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"businessUnitId" UUID,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"status" "RecordStatus" NOT NULL DEFAULT 'ACTIVE',FOREIGN KEY ("businessUnitId") REFERENCES "BusinessUnit"("id") ON DELETE SET NULL);
CREATE TABLE "InventoryStock" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"warehouseId" UUID NOT NULL REFERENCES "Warehouse"("id") ON DELETE CASCADE,"productId" UUID NOT NULL REFERENCES "Product"("id") ON DELETE RESTRICT,"quantity" NUMERIC(20,6) NOT NULL DEFAULT 0,"reservedQuantity" NUMERIC(20,6) NOT NULL DEFAULT 0);
CREATE TABLE "Account" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"accountType" TEXT NOT NULL,"status" "RecordStatus" NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE "FiscalPeriod" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"name" TEXT NOT NULL,"startsAt" TIMESTAMPTZ NOT NULL,"endsAt" TIMESTAMPTZ NOT NULL,"isClosed" BOOLEAN NOT NULL DEFAULT FALSE);
CREATE TABLE "JournalEntry" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"fiscalPeriodId" UUID NOT NULL REFERENCES "FiscalPeriod"("id") ON DELETE RESTRICT,"reference" TEXT NOT NULL,"status" "JournalStatus" NOT NULL DEFAULT 'DRAFT',"entryDate" TIMESTAMPTZ NOT NULL,"description" TEXT);
CREATE TABLE "JournalLine" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"journalEntryId" UUID NOT NULL REFERENCES "JournalEntry"("id") ON DELETE CASCADE,"accountId" UUID NOT NULL REFERENCES "Account"("id") ON DELETE RESTRICT,"debit" NUMERIC(20,6) NOT NULL DEFAULT 0,"credit" NUMERIC(20,6) NOT NULL DEFAULT 0,"description" TEXT);
CREATE TABLE "TaxCode" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"rate" NUMERIC(8,4) NOT NULL,"status" "RecordStatus" NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE "Vendor" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"email" TEXT,"status" "RecordStatus" NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE "PurchaseOrder" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"vendorId" UUID NOT NULL REFERENCES "Vendor"("id") ON DELETE RESTRICT,"number" TEXT NOT NULL,"status" "OrderStatus" NOT NULL DEFAULT 'DRAFT',"orderedAt" TIMESTAMPTZ);
CREATE TABLE "PurchaseLine" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"purchaseOrderId" UUID NOT NULL REFERENCES "PurchaseOrder"("id") ON DELETE CASCADE,"productId" UUID NOT NULL REFERENCES "Product"("id") ON DELETE RESTRICT,"quantity" NUMERIC(20,6) NOT NULL,"unitPrice" NUMERIC(20,6) NOT NULL);
CREATE TABLE "Customer" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"email" TEXT,"status" "RecordStatus" NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE "SalesOrder" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"customerId" UUID NOT NULL REFERENCES "Customer"("id") ON DELETE RESTRICT,"number" TEXT NOT NULL,"status" "OrderStatus" NOT NULL DEFAULT 'DRAFT',"orderedAt" TIMESTAMPTZ);
CREATE TABLE "SalesLine" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"salesOrderId" UUID NOT NULL REFERENCES "SalesOrder"("id") ON DELETE CASCADE,"productId" UUID NOT NULL REFERENCES "Product"("id") ON DELETE RESTRICT,"quantity" NUMERIC(20,6) NOT NULL,"unitPrice" NUMERIC(20,6) NOT NULL);
CREATE TABLE "Employee" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"employeeNumber" TEXT NOT NULL,"firstName" TEXT NOT NULL,"lastName" TEXT NOT NULL,"email" TEXT,"status" "EmployeeStatus" NOT NULL DEFAULT 'ACTIVE',"hiredAt" TIMESTAMPTZ NOT NULL);
CREATE TABLE "PayrollRun" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"name" TEXT NOT NULL,"periodStart" TIMESTAMPTZ NOT NULL,"periodEnd" TIMESTAMPTZ NOT NULL,"status" "PayrollStatus" NOT NULL DEFAULT 'DRAFT');
CREATE TABLE "PayrollEntry" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"payrollRunId" UUID NOT NULL REFERENCES "PayrollRun"("id") ON DELETE CASCADE,"employeeId" UUID NOT NULL REFERENCES "Employee"("id") ON DELETE RESTRICT,"gross" NUMERIC(20,6) NOT NULL,"deductions" NUMERIC(20,6) NOT NULL,"net" NUMERIC(20,6) NOT NULL);
CREATE TABLE "Lead" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"name" TEXT NOT NULL,"email" TEXT,"status" "LeadStatus" NOT NULL DEFAULT 'NEW');
CREATE TABLE "Opportunity" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"leadId" UUID,"name" TEXT NOT NULL,"value" NUMERIC(20,6) NOT NULL DEFAULT 0,"status" "OpportunityStatus" NOT NULL DEFAULT 'OPEN');
CREATE TABLE "Project" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"status" "ProjectStatus" NOT NULL DEFAULT 'PLANNING',"startsAt" TIMESTAMPTZ,"endsAt" TIMESTAMPTZ);
CREATE TABLE "ProjectTask" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"projectId" UUID NOT NULL REFERENCES "Project"("id") ON DELETE CASCADE,"name" TEXT NOT NULL,"status" "RecordStatus" NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE "BillOfMaterials" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"productId" UUID NOT NULL REFERENCES "Product"("id") ON DELETE RESTRICT,"version" TEXT NOT NULL,"status" "RecordStatus" NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE "ManufacturingOrder" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"productId" UUID NOT NULL REFERENCES "Product"("id") ON DELETE RESTRICT,"bomId" UUID NOT NULL REFERENCES "BillOfMaterials"("id") ON DELETE RESTRICT,"number" TEXT NOT NULL,"quantity" NUMERIC(20,6) NOT NULL,"status" "ManufacturingStatus" NOT NULL DEFAULT 'PLANNED');
CREATE TABLE "ReportDefinition" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"key" TEXT NOT NULL,"name" TEXT NOT NULL,"definition" JSONB NOT NULL,"status" "RecordStatus" NOT NULL DEFAULT 'ACTIVE');
CREATE UNIQUE INDEX "Organization_tenant_code" ON "Organization" ("tenantId","code");
CREATE UNIQUE INDEX "BusinessUnit_tenant_code" ON "BusinessUnit" ("tenantId","code");
CREATE UNIQUE INDEX "Currency_tenant_code" ON "Currency" ("tenantId","code");
CREATE UNIQUE INDEX "UnitOfMeasure_tenant_code" ON "UnitOfMeasure" ("tenantId","code");
CREATE UNIQUE INDEX "ProductCategory_tenant_code" ON "ProductCategory" ("tenantId","code");
CREATE UNIQUE INDEX "Product_tenant_sku" ON "Product" ("tenantId","sku");
CREATE UNIQUE INDEX "Warehouse_tenant_code" ON "Warehouse" ("tenantId","code");
CREATE UNIQUE INDEX "InventoryStock_tenant_wh_product" ON "InventoryStock" ("tenantId","warehouseId","productId");
CREATE UNIQUE INDEX "Account_tenant_code" ON "Account" ("tenantId","code");
CREATE UNIQUE INDEX "FiscalPeriod_tenant_name" ON "FiscalPeriod" ("tenantId","name");
CREATE UNIQUE INDEX "JournalEntry_tenant_reference" ON "JournalEntry" ("tenantId","reference");
CREATE UNIQUE INDEX "TaxCode_tenant_code" ON "TaxCode" ("tenantId","code");
CREATE UNIQUE INDEX "Vendor_tenant_code" ON "Vendor" ("tenantId","code");
CREATE UNIQUE INDEX "PurchaseOrder_tenant_number" ON "PurchaseOrder" ("tenantId","number");
CREATE UNIQUE INDEX "Customer_tenant_code" ON "Customer" ("tenantId","code");
CREATE UNIQUE INDEX "SalesOrder_tenant_number" ON "SalesOrder" ("tenantId","number");
CREATE UNIQUE INDEX "Employee_tenant_number" ON "Employee" ("tenantId","employeeNumber");
CREATE UNIQUE INDEX "PayrollRun_tenant_name" ON "PayrollRun" ("tenantId","name");
CREATE UNIQUE INDEX "PayrollEntry_tenant_run_employee" ON "PayrollEntry" ("tenantId","payrollRunId","employeeId");
CREATE UNIQUE INDEX "Project_tenant_code" ON "Project" ("tenantId","code");
CREATE UNIQUE INDEX "BOM_tenant_product_version" ON "BillOfMaterials" ("tenantId","productId","version");
CREATE UNIQUE INDEX "ManufacturingOrder_tenant_number" ON "ManufacturingOrder" ("tenantId","number");
CREATE UNIQUE INDEX "ReportDefinition_tenant_key" ON "ReportDefinition" ("tenantId","key");

-- Tenant-scoped operational tables. FORCE is intentional: table owners must not bypass RLS.
ALTER TABLE "Organization" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Organization" FORCE ROW LEVEL SECURITY;
ALTER TABLE "BusinessUnit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BusinessUnit" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Currency" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Currency" FORCE ROW LEVEL SECURITY;
ALTER TABLE "UnitOfMeasure" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UnitOfMeasure" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ProductCategory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductCategory" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Product" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Product" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Warehouse" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Warehouse" FORCE ROW LEVEL SECURITY;
ALTER TABLE "InventoryStock" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InventoryStock" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Account" FORCE ROW LEVEL SECURITY;
ALTER TABLE "FiscalPeriod" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FiscalPeriod" FORCE ROW LEVEL SECURITY;
ALTER TABLE "JournalEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "JournalEntry" FORCE ROW LEVEL SECURITY;
ALTER TABLE "JournalLine" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "JournalLine" FORCE ROW LEVEL SECURITY;
ALTER TABLE "TaxCode" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TaxCode" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Vendor" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Vendor" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PurchaseOrder" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PurchaseOrder" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PurchaseLine" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PurchaseLine" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Customer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Customer" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SalesOrder" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SalesOrder" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SalesLine" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SalesLine" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Employee" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Employee" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PayrollRun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PayrollRun" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PayrollEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PayrollEntry" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Lead" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Lead" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Opportunity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Opportunity" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Project" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Project" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ProjectTask" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProjectTask" FORCE ROW LEVEL SECURITY;
ALTER TABLE "BillOfMaterials" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BillOfMaterials" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ManufacturingOrder" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ManufacturingOrder" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ReportDefinition" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReportDefinition" FORCE ROW LEVEL SECURITY;
